---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: my-app
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: my-app@sha256:60e326c6e5f7e94b5dac440d04989c2e1166361b901dbd8bfe3ebce6c24e74bd
        namespace: shotclass
      name: latest
