# Use secrets for things which are actually secret like API keys, credentials, etc
# Base64 encode the values stored in a Kubernetes Secret: $ pbpaste | base64 | pbcopy
# The --decode flag is convenient: $ pbpaste | base64 --decode

apiVersion: v1
kind: Secret
metadata:
  name: pms-db
type: Opaque
data:
  MYSQL_DB_USER: cG1zZGJhZG1pbg==
  MYSQL_DB_PASSWORD: SW5jYWx1czE=
# REDIS_PASSWORD: AAZbUGVXeU5e0ZB